import type { PortRuleMatchType } from '../types'

export type ServiceCategory =
  | 'all'
  | 'ai'
  | 'social'
  | 'dev'
  | 'media'
  | 'game'
  | 'general'

export interface PresetService {
  id: string
  name: string
  category: Exclude<ServiceCategory, 'all'>
  description: string
  domains: string[]
  matchType: PortRuleMatchType
  iconKey: string
  color: string
}

export const SERVICE_CATEGORIES: { id: ServiceCategory; label: string }[] = [
  { id: 'all', label: '全部' },
  { id: 'ai', label: 'AI 大模型' },
  { id: 'social', label: '社交通讯' },
  { id: 'dev', label: '开发与工作' },
  { id: 'media', label: '流媒体影音' },
  { id: 'game', label: '游戏平台' },
  { id: 'general', label: '综合常用' },
]

export const PRESET_SERVICES: PresetService[] = [
  // --- AI 大模型 ---
  {
    id: 'openai',
    name: 'OpenAI / ChatGPT',
    category: 'ai',
    description: 'ChatGPT、API、Sora 及静态全链路',
    domains: [
      'chatgpt.com',
      'openai.com',
      'oaistatic.com',
      'oaiusercontent.com',
      'chat.com',
      'sora.com',
      'ai.com',
    ],
    matchType: 'domain-suffix',
    iconKey: 'bot',
    color: 'emerald',
  },
  {
    id: 'claude',
    name: 'Claude (Anthropic)',
    category: 'ai',
    description: 'Claude 网页、对话与 Anthropic API',
    domains: ['claude.ai', 'anthropic.com', 'claudeusercontent.com'],
    matchType: 'domain-suffix',
    iconKey: 'sparkles',
    color: 'amber',
  },
  {
    id: 'gemini',
    name: 'Google Gemini (AI)',
    category: 'ai',
    description: 'Gemini 对话、AI Studio 与 Google AI API',
    domains: [
      'gemini.google.com',
      'aistudio.google.com',
      'makersuite.google.com',
      'generativelanguage.googleapis.com',
      'ai.google.dev',
      'bard.google.com',
      'deepmind.google',
    ],
    matchType: 'domain-suffix',
    iconKey: 'brain',
    color: 'blue',
  },
  {
    id: 'copilot',
    name: 'Microsoft Copilot',
    category: 'ai',
    description: '微软 Copilot 助手与 Bing AI',
    domains: [
      'copilot.microsoft.com',
      'sydneydiscussion.bing.com',
      'bingapis.com',
      'githubcopilot.com',
    ],
    matchType: 'domain-suffix',
    iconKey: 'cpu',
    color: 'slate',
  },
  {
    id: 'cursor',
    name: 'Cursor AI',
    category: 'ai',
    description: 'Cursor 代码编辑器云端推理与更新服务',
    domains: ['cursor.com', 'cursor.sh'],
    matchType: 'domain-suffix',
    iconKey: 'code-xml',
    color: 'purple',
  },
  {
    id: 'perplexity',
    name: 'Perplexity AI',
    category: 'ai',
    description: 'Perplexity 智能搜索与 API',
    domains: ['perplexity.ai', 'pplx.ai'],
    matchType: 'domain-suffix',
    iconKey: 'search-code',
    color: 'cyan',
  },
  {
    id: 'groq',
    name: 'Groq',
    category: 'ai',
    description: 'LPU 超高速云端推理平台',
    domains: ['groq.com'],
    matchType: 'domain-suffix',
    iconKey: 'zap',
    color: 'orange',
  },
  {
    id: 'midjourney',
    name: 'Midjourney',
    category: 'ai',
    description: 'Midjourney 绘图与 Web 平台',
    domains: ['midjourney.com'],
    matchType: 'domain-suffix',
    iconKey: 'image',
    color: 'indigo',
  },
  {
    id: 'huggingface',
    name: 'Hugging Face',
    category: 'ai',
    description: '开源 AI 模型与数据集社区',
    domains: ['huggingface.co', 'hf.space'],
    matchType: 'domain-suffix',
    iconKey: 'smile',
    color: 'yellow',
  },

  // --- 社交通讯 ---
  {
    id: 'twitter',
    name: 'X (Twitter)',
    category: 'social',
    description: '推特网页、客户端、静态资源与 x.ai',
    domains: ['x.com', 'twitter.com', 'twimg.com', 't.co', 'x.ai'],
    matchType: 'domain-suffix',
    iconKey: 'twitter',
    color: 'slate',
  },
  {
    id: 'telegram',
    name: 'Telegram',
    category: 'social',
    description: 'Telegram 即时通讯与短链服务',
    domains: [
      'telegram.org',
      't.me',
      'telegra.ph',
      'telegram.me',
      'telesco.pe',
      'tdesktop.com',
    ],
    matchType: 'domain-suffix',
    iconKey: 'send',
    color: 'sky',
  },
  {
    id: 'discord',
    name: 'Discord',
    category: 'social',
    description: 'Discord 语音、社区频道与 CDN',
    domains: [
      'discord.com',
      'discord.gg',
      'discordapp.com',
      'discordapp.net',
      'discordstatus.com',
    ],
    matchType: 'domain-suffix',
    iconKey: 'message-square',
    color: 'indigo',
  },
  {
    id: 'reddit',
    name: 'Reddit',
    category: 'social',
    description: 'Reddit 社区讨论与多媒体服务',
    domains: ['reddit.com', 'redd.it', 'redditstatic.com', 'redditmedia.com'],
    matchType: 'domain-suffix',
    iconKey: 'message-circle',
    color: 'orange',
  },
  {
    id: 'instagram',
    name: 'Instagram',
    category: 'social',
    description: 'Instagram 社交图片与视频服务',
    domains: ['instagram.com', 'cdninstagram.com'],
    matchType: 'domain-suffix',
    iconKey: 'camera',
    color: 'rose',
  },
  {
    id: 'facebook',
    name: 'Meta (Facebook)',
    category: 'social',
    description: 'Facebook、Messenger 与 Meta 生态',
    domains: ['facebook.com', 'fbcdn.net', 'fb.com', 'meta.com'],
    matchType: 'domain-suffix',
    iconKey: 'share-2',
    color: 'blue',
  },
  {
    id: 'threads',
    name: 'Threads',
    category: 'social',
    description: 'Meta 旗下文字分享社区',
    domains: ['threads.net'],
    matchType: 'domain-suffix',
    iconKey: 'at-sign',
    color: 'neutral',
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    category: 'social',
    description: 'TikTok 短视频国际版与 CDN',
    domains: [
      'tiktok.com',
      'byteoversea.com',
      'ibytedtos.com',
      'tiktokcdn.com',
      'tiktokv.com',
    ],
    matchType: 'domain-suffix',
    iconKey: 'video',
    color: 'stone',
  },

  // --- 开发与工作 ---
  {
    id: 'github',
    name: 'GitHub',
    category: 'dev',
    description: 'GitHub 代码托管、资源库与 Pages',
    domains: [
      'github.com',
      'githubassets.com',
      'githubusercontent.com',
      'github.io',
      'ghcr.io',
    ],
    matchType: 'domain-suffix',
    iconKey: 'github',
    color: 'zinc',
  },
  {
    id: 'docker',
    name: 'Docker Hub',
    category: 'dev',
    description: 'Docker 镜像注册表与下载服务',
    domains: ['docker.com', 'docker.io'],
    matchType: 'domain-suffix',
    iconKey: 'container',
    color: 'blue',
  },
  {
    id: 'notion',
    name: 'Notion',
    category: 'dev',
    description: 'Notion 笔记与工作区协同',
    domains: ['notion.so', 'notion.site', 'notion.com'],
    matchType: 'domain-suffix',
    iconKey: 'book-open',
    color: 'slate',
  },
  {
    id: 'figma',
    name: 'Figma',
    category: 'dev',
    description: 'Figma 在线设计与协同工具',
    domains: ['figma.com'],
    matchType: 'domain-suffix',
    iconKey: 'pen-tool',
    color: 'pink',
  },
  {
    id: 'slack',
    name: 'Slack',
    category: 'dev',
    description: 'Slack 团队即时通讯与边缘网络',
    domains: ['slack.com', 'slack-edge.com'],
    matchType: 'domain-suffix',
    iconKey: 'hash',
    color: 'emerald',
  },
  {
    id: 'stackoverflow',
    name: 'Stack Overflow',
    category: 'dev',
    description: '开发者问答社区与技术网络',
    domains: ['stackoverflow.com', 'stackexchange.com'],
    matchType: 'domain-suffix',
    iconKey: 'help-circle',
    color: 'amber',
  },
  {
    id: 'vercel',
    name: 'Vercel',
    category: 'dev',
    description: '前端云平台与边缘部署服务',
    domains: ['vercel.com', 'vercel.app'],
    matchType: 'domain-suffix',
    iconKey: 'triangle',
    color: 'stone',
  },

  // --- 流媒体影音 ---
  {
    id: 'youtube',
    name: 'YouTube',
    category: 'media',
    description: 'YouTube 视频、直播与全量音视频 CDN',
    domains: [
      'youtube.com',
      'googlevideo.com',
      'ytimg.com',
      'youtu.be',
      'yt.be',
    ],
    matchType: 'domain-suffix',
    iconKey: 'play-square',
    color: 'red',
  },
  {
    id: 'netflix',
    name: 'Netflix',
    category: 'media',
    description: 'Netflix 影视点播与全量视频 CDN',
    domains: [
      'netflix.com',
      'netflix.net',
      'nflxext.com',
      'nflximg.net',
      'nflxvideo.net',
      'nflxso.net',
    ],
    matchType: 'domain-suffix',
    iconKey: 'film',
    color: 'rose',
  },
  {
    id: 'spotify',
    name: 'Spotify',
    category: 'media',
    description: 'Spotify 音乐流媒体与 CDN',
    domains: ['spotify.com', 'spotifycdn.com', 'scdn.co', 'spoti.fi'],
    matchType: 'domain-suffix',
    iconKey: 'music',
    color: 'green',
  },
  {
    id: 'disney',
    name: 'Disney+',
    category: 'media',
    description: '迪士尼+ 流媒体视频点播',
    domains: ['disneyplus.com', 'dssott.com', 'disney-portal.my.onetrust.com'],
    matchType: 'domain-suffix',
    iconKey: 'tv',
    color: 'sky',
  },
  {
    id: 'twitch',
    name: 'Twitch',
    category: 'media',
    description: '游戏直播与互动视频平台',
    domains: ['twitch.tv', 'ttvnw.net', 'jtvnw.net'],
    matchType: 'domain-suffix',
    iconKey: 'radio',
    color: 'purple',
  },

  // --- 游戏平台 ---
  {
    id: 'steam',
    name: 'Steam',
    category: 'game',
    description: 'Steam 商店、社区、好友与下载 CDN',
    domains: [
      'steampowered.com',
      'steamcommunity.com',
      'steamstatic.com',
      'steamcontent.com',
    ],
    matchType: 'domain-suffix',
    iconKey: 'gamepad-2',
    color: 'slate',
  },
  {
    id: 'epic',
    name: 'Epic Games',
    category: 'game',
    description: 'Epic 游戏商城与虚幻引擎服务',
    domains: ['epicgames.com', 'unrealengine.com'],
    matchType: 'domain-suffix',
    iconKey: 'swords',
    color: 'neutral',
  },
  {
    id: 'playstation',
    name: 'PlayStation Network',
    category: 'game',
    description: '索尼 PSN 商店与网络联机服务',
    domains: [
      'playstation.com',
      'playstation.net',
      'sonyentertainmentnetwork.com',
    ],
    matchType: 'domain-suffix',
    iconKey: 'play',
    color: 'blue',
  },

  // --- 综合常用 ---
  {
    id: 'google',
    name: 'Google (全生态)',
    category: 'general',
    description: 'Google 搜索、API、Drive、Maps 等核心全家桶',
    domains: [
      'google.com',
      'googleapis.com',
      'gstatic.com',
      'googleusercontent.com',
      'ggpht.com',
      'gvt1.com',
      'google.com.hk',
      '1e100.net',
    ],
    matchType: 'domain-suffix',
    iconKey: 'globe',
    color: 'blue',
  },
  {
    id: 'wikipedia',
    name: 'Wikipedia 维基百科',
    category: 'general',
    description: '维基百科与自由多媒体档案',
    domains: ['wikipedia.org', 'wikimedia.org'],
    matchType: 'domain-suffix',
    iconKey: 'library',
    color: 'stone',
  },
  {
    id: 'amazon',
    name: 'Amazon 亚马逊',
    category: 'general',
    description: '亚马逊全球电商与零售服务',
    domains: ['amazon.com', 'media-amazon.com'],
    matchType: 'domain-suffix',
    iconKey: 'shopping-cart',
    color: 'amber',
  },
]
